In [1]:
import pandas as pd

In [2]:
import random

In [3]:
# 1. Definimos la cantidad de filas deseadas (1 millón)
cantidad = 1000000

In [8]:
# 2. Conjunto de datos base reales/coherentes para la simulación de Cancún
influencers_pool = ["@Mon laferte", "@Caifanes_mx", "@heroes del silencio", "@Zoe", "@chicahernandez", "@Aleman"]
tipos_post_pool = ["foto", "video", "reel", "carrusel"]
fechas_pool = ["2026-05-01", "2026-05-10", "2026-05-15", "2026-05-20", "2026-05-24"]

In [9]:
# 3. Creación del DataFrame de 1,000,000 de registros usando comprensión de listas
df_instagram = pd.DataFrame({
    "influencer": [random.choice(influencers_pool) for _ in range(cantidad)],
    "likes": [random.randint(100, 50000) for _ in range(cantidad)],  # Rango de likes realista
    "comentarios": [random.randint(5, 2500) for _ in range(cantidad)],  # Rango de comentarios realista
    "fecha": [random.choice(fechas_pool) for _ in range(cantidad)],
    "tipo_post": [random.choice(tipos_post_pool) for _ in range(cantidad)]
})

In [10]:
# Definimos la cantidad (1 millón de registros)
cantidad = 1000000

In [11]:
df_instagram.shape

(1000000, 5)

In [12]:
df_instagram.dtypes

influencer     object
likes           int64
comentarios     int64
fecha          object
tipo_post      object
dtype: object

In [13]:
df_instagram.head()

             influencer  likes  comentarios       fecha tipo_post
0               @Aleman  23693         2048  2026-05-24  carrusel
1  @heroes del silencio  48310         1912  2026-05-01      reel
2                  @Zoe   2862          468  2026-05-20  carrusel
3          @Caifanes_mx  40248          869  2026-05-20      reel
4       @chicahernandez  41176         2474  2026-05-24      foto

In [14]:
df_instagram.memory_usage(deep=True).sum() / (1024**2)

np.float64(181.12032413482666)

In [15]:
print("Promedio de Likes:", df_instagram["likes"].mean())
print("Promedio de Comentarios:", df_instagram["comentarios"].mean())

Promedio de Likes: 25064.59876
Promedio de Comentarios: 1252.57808

In [16]:
df_instagram.groupby("tipo_post")[["likes", "comentarios"]].mean()

                  likes  comentarios
tipo_post
carrusel   25073.445151  1252.055678
foto       25068.935076  1254.305667
reel       25035.486402  1250.969756
video      25080.604586  1252.981806

In [18]:
df_instagram.groupby("influencer")["likes"].sum().sort_values(ascending=False)

influencer
@Zoe                    4179365472
@heroes del silencio    4178263112
@chicahernandez         4177707245
@Mon laferte            4177058485
@Caifanes_mx            4176748131
@Aleman                 4175456315
Name: likes, dtype: int64